# Generated by Django 2.2 on 2019-04-08 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=100)),
                ('_from', models.DateField()),
                ('to', models.DateField(blank=True)),
                ('gpa', models.CharField(blank=True, max_length=10)),
                ('grade', models.CharField(blank=True, max_length=30)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='developer.Developer')),
            ],
        ),
    ]
