# Generated by Django 2.2 on 2019-04-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_auto_20190408_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='mobile',
            field=models.CharField(error_messages={'required': 'The number must be in Nigerian Mobile format'}, max_length=11),
        ),
    ]
