# Generated by Django 2.2 on 2019-04-10 13:31

import developer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0003_auto_20190410_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='mobile',
            field=models.CharField(blank=True, error_messages={'unique': 'A user already registered with this mobile number'}, max_length=11, null=True, unique=True, validators=[developer.models.validate_mobile_number]),
        ),
    ]
