# Generated by Django 2.2 on 2019-04-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0004_auto_20190408_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='mobile',
            field=models.CharField(error_messages={'unique': 'A user already registered with this mobile number'}, max_length=11),
        ),
    ]
