# Generated by Django 2.2 on 2019-04-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0006_auto_20190408_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with the same email already exist'}, max_length=254, unique=True),
        ),
    ]
