# Generated by Django 2.2 on 2019-04-08 18:54

import developer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0007_auto_20190408_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='mobile',
            field=models.CharField(error_messages={'unique': 'A user already registered with this mobile number'}, max_length=11, unique=True, validators=[developer.models.validate_mobile_number]),
        ),
    ]
